<table>
  <thead>
    <tr>
      <th>company</th>
      <th>employee_number</th>
      <th>employee_code</th>
      <th>employee_name</th>
      <th>log_date</th>
      <th>time_in_from</th>
      <th>time_in_to</th>
      <th>time_out_from</th>
      <th>time_out_to</th>
      <th>working_hours</th>
    </tr>
  </thead>
</table>